# Copyright (C) 2016 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
server:
  #port: 8080
  compression:
    enabled: true
    mime-types: application/hal+json
    min-response-size: 2KB
  error.whitelabel.enabled: false
  http2.enabled: true
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3
    key-alias: microservice
    key-password: zimmermann
    key-store: classpath:keystore.p12
    key-store-password: zimmermann
    key-store-type: PKCS12
    protocol: TLS
    trust-store: classpath:truststore.p12
    trust-store-password: zimmermann
    trust-store-type: PKCS12
  shutdown: graceful

spring:
  application.name: artikel
  aop.proxy-target-class: false
  data.mongodb:
    authentication-database: admin
    auto-index-creation: false
    database: acme
    #host: localhost
    #password: p
    #port: 27017
    repositories.type: none
    # https://docs.mongodb.com/manual/reference/connection-string
    # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[database][?options]]
    #uri: mongodb://admin:p@localhost/acme?replicaSet=replicaSet&authSource=admin&authMechanism=SCRAM-SHA-256
    username: admin
    uuid-representation: standard
  jackson.default-property-inclusion: non_null
  lifecycle.timeout-per-shutdown-phase: 3s
  mail:
    host: localhost
    port: 5025
    #protocol: smtp
    properties.mail:
      debug: false
      smtp:
        auth: false
        starttls.enable: false
    # Mailserver des IZ
    #host: smtp.h-ka.de
    #port: 23
    #username: nnvv0011
    #password: blabla
    # GMail
    #host: smtp.gmail.com
    #port: 587
    #properties.mail.smtp.starttls.enable: true
  main:
    lazy-initialization: true
    web-application-type: reactive
  security.user.password: p
  spel.ignore: true

info.app:
  author: Juergen Zimmermann
  lecture: Softwarearchitektur
  semester: 3
  studiengang: Wirtschaftsinformatik und Microservices

management.endpoints.web.exposure.include: "*"

# --------------------------------------------------------
# E i g e n e   P r o p e r t i e s
# --------------------------------------------------------
mail:
  from: Theo Test <theo@test.de>
  sales: Maxi Musterfrau <maxi.musterfrau@test.de>

---
# alternativ: azure_app_service, sap, heroku
spring.config.activate.on-cloud-platform: kubernetes
management.endpoint.health:
  enabled: true
  probes.enabled: true
  show-details: ALWAYS
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s

---
spring:
  config.activate.on-profile: dev
  #http.log-request-details: true
  # siehe org.springframework.boot.autoconfigure.jackson.JacksonProperties
  jackson.serialization.indent-output: true
  # -Dreactor.trace.operatorStacktrace=true
  reactor.debugagent.enabled: true
  # Pfad fuer GraphQL: /graphql
  # Pfad für GraphiQL: /graphiql
  # Pfad für Schema:   /graphql/schema
  graphql.schema.printer.enabled: true
  #devtools:
  #  livereload.enabled: false
  #  restart.trigger-file: /restart.txt

artikel:
  password: p
  password-falsch: FALSCH
