GET {{baseUrl}}/api
Accept: application/hal+json
ALPN: h2

###

GET {{baseUrl}}/api/1
Accept: application/hal+json
ALPN: h2

###

# Fehlermeldung 404
GET {{baseUrl}}/api/10
Accept: application/hal+json
ALPN: h2

###

GET {{baseUrl}}/api?name=hallo
Accept: application/hal+json
ALPN: h2

###

GET{{baseUrl}}/api?einkaufsPreis=2
Accept: application/hal+json
ALPN: h2
