@startuml
package kotlinx.coroutines.flow {
    interface Flow
    interface Map
}

package com.acme.artikel {
    package entity {
        class Artikel << entity >>
    }

    package service {
        class ArtikelReadService << control >> << @Service >> {
            + suspend findById(id: Int?) : FindByIdResult
            + suspend find(suchkriterien: Map<String, String>): Flow<Artikel>
            - findAll() : Flow<Artikel>
            - findByNachname(name: String): Flow<Artikel>
            - findByEinkaufspreis(einkaufspreis: Int): Flow<Artikel>
            - findByVerkaufspreis(verkaufspreis: Int): Flow<Artikel>
            - findByBestand(bestand: Int): Flow<Artikel>
        }

        ArtikelReadService .up.> Artikel
        ArtikelReadService ..> Flow
        ArtikelReadService .up.> Map
    }
}
hide empty members
@enduml
