@startuml

package com.acme.artikel.entity {

    class Artikel << entity >> {
    - id : Int?
    - name : String
    - einkaufsPreis : Int
    - verkaufsPreis : Int
    - bestand : Int
    }

}
hide empty members
@enduml
