@startuml

package org.springframework {
    package web.bind.annotation {
        interface "@PathVariable" as PathVariable

        interface "@RequestParam" as RequestParam
    }

    package hateoas {
            class CollectionModel<E>
        }

    package http {
        class ResponseEntity<T>

        package server.reactive {
            interface ServerHttpRequest
        }
    }
}

package kotlin.collections {
    interface Map
}

package java.util {
    class UUID
}

package com.acme.artikel {

    package service {
        class ArtikelReadService << control >> << @Service >>
    }

    package rest {
        class ArtikelGetController << boundary >> << @RestController >> << @RequestMapping >> {
            + @GetMapping suspend findById(@PathVariable id: UUID?) : ResponseEntity<ArtikelModel>
            + @GetMapping suspend find(@RequestParam queryParams: Map<String, String>): ResponseEntity<CollectionModel<ArtikelModel>>
        }

        class ArtikelModel << entity >>

        ArtikelGetController o-right-> "1" ArtikelReadService : service

        ArtikelGetController .up.> ResponseEntity
        ArtikelGetController .up.> CollectionModel
        ArtikelGetController .down.> ArtikelModel
        ArtikelGetController .up.> ServerHttpRequest
        ArtikelGetController .up.> PathVariable
        ArtikelGetController .up.> RequestParam

        ArtikelGetController .up.> Map

        ArtikelGetController .up.> UUID

    }
}

hide empty members

@enduml
